USE [master]
GO

/****** Object:  Database [AppleInc]    Script Date: 2/4/2021 5:38:20 PM ******/
CREATE DATABASE [AppleInc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppleInc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.TRAININGSERVER\MSSQL\DATA\AppleInc.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AppleInc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.TRAININGSERVER\MSSQL\DATA\AppleInc_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppleInc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AppleInc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AppleInc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AppleInc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AppleInc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AppleInc] SET ARITHABORT OFF 
GO

ALTER DATABASE [AppleInc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AppleInc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AppleInc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AppleInc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AppleInc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AppleInc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AppleInc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AppleInc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AppleInc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AppleInc] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AppleInc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AppleInc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AppleInc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AppleInc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AppleInc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AppleInc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AppleInc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AppleInc] SET RECOVERY FULL 
GO

ALTER DATABASE [AppleInc] SET  MULTI_USER 
GO

ALTER DATABASE [AppleInc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AppleInc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AppleInc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AppleInc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AppleInc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AppleInc] SET QUERY_STORE = OFF
GO

USE [AppleInc]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [AppleInc] SET  READ_WRITE 
GO

